export const FILTER_BY_BREED = 'FILTER_BY_BREED'
export const FILTER_BY_TEMPERAMENT = 'FILTER_BY_TEMPERAMENT'
export const ORDER = 'ORDER'
export const GET_DOGS = 'GET_DOGS'
export const GET_DOG ='GET_DOG'
export const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS'
export const CREATE_DOG = 'CREATE_DOG'
